name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
configure: config.sync

# Information added by Drupal.org packaging script on 2020-06-03
version: '9.0.0'
project: 'drupal'
datestamp: 1591221734
